//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamerShop_v1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Key
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Key()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int IdKey { get; set; }
        public Nullable<int> IdGame { get; set; }
        public string Key1 { get; set; }
        public Nullable<bool> IsSoldOut { get; set; }
    
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }

        public string GetSoldOutStatus
        {
            get
            {
                if ((bool)IsSoldOut)
                    return "Да";
                else
                    return "Нет";
            }
        }
    }
}
