//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamerShop_v1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int IdSale { get; set; }
        public Nullable<int> IdKey { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Key Key { get; set; }

        public string GetGameTitle
        {
            get
            {
                return Key.Game.GameTitle;
            }
        }

        public string GetPhoto
        {
            get
            {
                return Key.Game.GetPhoto;
            }
        }

        public string GetClient
        {
            get
            {
                if (IdClient == null)
                    return "DELETED USER";
                else
                {
                    if (IdClient == Client.IdClient)
                        return Convert.ToString(Client.ClientLogin);
                    else
                        return "";
                }
            }
        }
    }
}
